---
driver:
  name: dokken
  privileged: true
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
  - name: ubuntu-14.04
    driver:
      image: dokken/ubuntu-14.04
      pid_one_command: /sbin/init
      pull_platform: linux/amd64

  - name: ubuntu-22.04
    driver:
      image: dokken/ubuntu-22.04
      pid_one_command: /bin/systemd
      pull_platform: linux/amd64

  - name: ubuntu-24.04
    driver:
      image: dokken/ubuntu-24.04
      pid_one_command: /bin/systemd
      pull_platform: linux/amd64

  - name: centos-7
    driver:
      image: dokken/centos-7
      pid_one_command: /usr/lib/systemd/systemd
      pull_platform: linux/amd64

  - name: almalinux-8
    driver:
      image: dokken/almalinux-8
      pid_one_command: /usr/lib/systemd/systemd
      pull_platform: linux/amd64

  - name: almalinux-9
    driver:
      image: dokken/almalinux-9
      pid_one_command: /usr/lib/systemd/systemd
      pull_platform: linux/amd64

suites:
  - name: default
    run_list:
      - recipe[incron-next::default]
    attributes:
  - name: local-source
    run_list:
      - recipe[incron-next::default]
    attributes:
      incron:
        version: '0.5.12'
        use_local_source: true