---
driver:
  name: vagrant

verifier:
  name: inspec
  backend_cache: false

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-22.04
  - name: ubuntu-24.04
  - name: centos-stream-9
  - name: almalinux-9
  - name: rockylinux-9

suites:
  - name: default
    run_list:
      - recipe[incron-next::default]
    attributes:
  - name: local-source
    run_list:
      - recipe[incron-next::default]
    attributes:
      incron:
        version: '0.5.12'
        use_local_source: true
